### ISSUE TITLE
Get Started Link Suggestion

### ISSUE THREAD

**Issue by w3cj** [coollabsio/coolify.io#1]
Right now ["Get Started" on the self-host landing page](https://github.com/coollabsio/coolify.io/blob/main/src/pages/self-hosted.astro#L13) points to the github README.

Every time I click this, I wish it took me to the docs instead.

I think any of these would be a better spot to link to:
* https://coolify.io/docs/introduction
* https://coolify.io/docs/quickstart
* https://coolify.io/docs/installation

**Comment by andrasbacsai** [comment]
It make sense, thank you. I will change it.
