### ISSUE TITLE
Website suggestion

### ISSUE THREAD

**Issue by ZilloweZ** [coollabsio/coolify.io#3]
I think it would be better and easier if your site and the docs using one framework, especially the docs, I think it would be better if you use something like [Vitepress](https://vitepress.dev) for both.
It uses markdown, and you can set a home page, and it's pretty easy.
I made a docs using that if you want an example.
This is just a suggestion, you do what you want, I just want to help.

**Comment by ZilloweZ** [comment]
The example project can be found here <https://codeberg.org/ZilloweZ/Vitepress-Example>.

**Comment by andrasbacsai** [comment]
Thanks for the suggestion, but I will keep it like this. It is simple and just works. :)
