### ISSUE TITLE
Fix favicon to be shown on search engines

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify.io#5]
![image](https://github.com/user-attachments/assets/a369a2de-c88d-4bd7-8ae6-18e8c36cb64e)

**Comment by ALsJourney** [comment]
https://realfavicongenerator.net/favicon_checker?protocol=https&site=coolify.io

After doing checks seems like the favicon is ill-formed... let me add new favicons

**Comment by ALsJourney** [comment]
-- created PR #6

**Comment by andrasbacsai** [comment]
We will see in a few days - I guess.

**Comment by ALsJourney** [comment]
> We will see in a few days - I guess.

![CleanShot 2024-08-23 at 20 01 16@2x](https://github.com/user-attachments/assets/00b6afbc-81d7-4532-bb12-2e61948b6b6c)
😎
