### ISSUE TITLE
Plunk service not up

### ISSUE THREAD

**Issue by raphaelromao** [coollabsio/coolify.io#7]
Hi, first of all, congratulations on the coolify project!

I'm trying to install Plunk on my server, but it's always on the web (404 page not found) when I access the service.

I would like to know if I made a mistake, I made a mistake.

I am leaving a URL and name Default service and still it doesn't work.

**Comment by raphaelromao** [comment]
It seems that I can now get the service up and running, but I can't create an account or log in.

**Comment by raphaelromao** [comment]
![Captura de Tela 2024-10-02 às 22 08 03](https://github.com/user-attachments/assets/88dbb6b0-7b2c-483b-9e4f-110e4bc6e9a7)

**Comment by andrasbacsai** [comment]
This is the wrong repository to report this. Please use https://github.com/coollabsio/coolify
